cdba.c

cdba will choke with 'is not a regular file' message if one specifies
symlink as a boot file argument. Support using symlinks as a boot file.
Signed-off-by: Dmitry Baryshkov <dbaryshkov@gmail.com>

cdba: allow specifying symlink as a boot file

---

cdba-server.c
device.c

To ease debugging connectivity vs bootloader vs early boot issues add two notifications on the server side:
- when fastboot connection is opened
- before sending fastboot commands to the device

Add two notifications from server side

---

99-libftdi.rules
Makefile
device_parser.c
ftdi-gpio.c
ftdi-gpio.h

This permits driving a board controlled by GPIOs on an FTDI interface.
Also add a sample 99-libftdi.rules to permit using the FTDI device.
Signed-off-by: Neil Armstrong <neil.armstrong@linaro.org>

Add generic ftdi GPIO backend

---

.github/workflows/ci.yml
.github/workflows/codeql-analysis.yml
ci/archlinux.sh
ci/debian.cross-compile.sh
ci/debian.i386.sh
ci/debian.sh
ci/fedora.sh
ci/ubuntu.cross-compile.sh
ci/ubuntu.i386.sh
ci/ubuntu.sanitizers.sh
ci/ubuntu.sh

Add Continuous Integration using Github actions, re-using similar setup from linux-nfc/neard [1] (dropped Alpine, Ubuntu i386, sanitizers and few others action steps).  Since I copied most files, I retained all original copyrights.
The CI will build cdba for several different distros and architectures.
The Fedora builds will fail, because it does not have libftdi-compat (or libftdi1) package.
[1] https://github.com/linux-nfc/neard

ci: add basic Github Actions Continuous Integration builds

---

Makefile
cdb_assist.c
cdba-server.c
cdba.c
circ_buf.c
conmux.c
device.c
device_parser.c
fastboot.c
ftdi-gpio.c
list.h

Enable several warnings and fix them. Enable also -Werror so any new warnings will be always spotted.

Fix some GCC and clang warnings

---

cdba-server.c

Don't count the timers, as it's not used anywhere. Clang is unhappy with that:
cdba-server.c:307:6: warning: variable 'count' set but not used [-Wunused-but-set-variable]
int count = 0;

cdba-server: Remove dead code

---

device.c
device.h
device_parser.c

For different reasons it might be desirable to keep slot 'b' as an active slot. Add support for specifying the active slot in the config file. The default is still slot 'a'.

device: support specifying active slot

---

.github/workflows/ci.yml
Makefile
ci/archlinux.sh
ci/debian.sh

Use the cflags and libs from pkg-config. This allows us to adapt to the distro differences. Also, make sure to autodetect if the distro provides libftdi or libftdi1, preferring the latter one.

Makefile: adapt for libftdi vs libftdi1 differences

---

.github/workflows/ci.yml

Newer ARMv7 boards are actually supported by armhf, not armel.  armel containers might not even work:
The following packages have unmet dependencies:
libc6-dev:armel : Depends: linux-libc-dev:armel but it is not installable
E: Unable to correct problems, you have held broken packages.

ci: use Debian ARM hard-float port instead of armel

---

README
cdba-server.c
device.c
device.h
device_parser.c
shell/cdba-shell

Implement ACL support to limit visibility of the boards.  This allows one to e.g. limit visibility of some of the customer boards to the certain groups of users, while keeping the rest of the lab generally visible to all remote cdba users.

add ACL support

---

Makefile
device.c
device.h
device_parser.c
ppps.c
ppps.h

Since Linux kernel 6.0, PPPS capable USB hubs expose a simple sysfs attribute for power control. Allow overwriting the usb control callback to use PPPS hub control instead.
This really simply allows for combining a PPPS hub with some other control board like a micro controller implementing the qcomlt_debug_board interface.

support ppps usb control

---

README
ci/archlinux.sh
ci/debian.cross-compile.sh
ci/debian.i386.sh
ci/debian.sh
ci/fedora.sh
device.h
device_parser.c
device_parser.h
local-gpio-v1.c
local-gpio-v2.c
local-gpio.c
local-gpio.h
meson.build

This driver permits controlling local (on the system) gpios by using the libgpiod library

Add local gpio control

---

device.h
device_parser.c
ppps.c

Some devices / hubs require switching both USB-2 and USB-3 ports to function correctly. Add ppps3_path device option to control USB-3 port in addition to the USB-2 port.
cc @calebccff

ppps: add support for separate USB-3 PPPS path

---

ftdi-gpio.c

Since the FTDI is hot-pluggable, the output lines can be protected for unwanted changes by a supplementary GPIO that allows the FTDI gpio outputs to be enabled for the required functions.
Closes: #43

ftdi_gpio: add output_enable gpio type

---

.github/workflows/ci.yml
meson.build
meson_options.txt

It is expected that the majority of CDBA users do not need the server binary. Allow users to disable the cdba-server binary and build just the client.
Fixes #48

meson: support client-only builds

---

README
local-gpio.c

As discussed in https://github.com/linux-msm/cdba/pull/46#discussion_r1379831140:
Instead of:
```
local_gpio:
- power: 
chip: gpiochip0
line: 7
active_low: true
- fastboot_key:
chip: gpiochip0
line: 8
active_low: true
- power_key:
chip: gpiochip0
line: 14
active_low: true
- usb_disconnect:
chip: gpiochip1
line: 4
```
Accept the following:
```
local_gpio:
power:
chip: gpiochip0
line: 7
active_low: true
fastboot_key:
chip: gpiochip0
line: 8
active_low: true
power_key:
chip: gpiochip0
line: 14
active_low: true
usb_disconnect:
chip: gpiochip1
line: 4
```
It's simpler and clearer.

local_gpio: simplify yaml description

---

README
device_parser.c
ftdi-gpio.c

Switch from:
```
ftdi_gpio: "s:0xVEND:0xPROD:SERIAL;D;POWER,0,ACTIVE_LOW;FASTBOOT_KEY,1,ACTIVE_HIGH;POWER_KEY,2,ACTIVE_HIGH;USB_DISCONNECT,3,ACTIVE_LOW"
```
to 
```
ftdi_gpio:
vendor: "0xVEND"
product: "0xPROD"
serial: SERIAL
power:
interface: D
line: 7
active_low: true
fastboot_key:
interface: D
line: 8
active_low: true
power_key:
interface: D
line: 3
active_low: true
usb_disconnect:
interface: D
line: 2
```
but still accept the previous format with a warning
Follows schema specified in #46  https://github.com/linux-msm/cdba/pull/46/files#diff-de05320774ffa1b4e469ebacba38ff3001bf8c561d85c6f5d8410c5adeea3455R92
Closes: #42

Ftdi gpio yaml parsing

---

.github/workflows/ci.yml
cdba-server.c
cdba.c
ci/alpine.sh
meson.build

Enabling -Werror by default sucks for everyone who isn't maintaining
CDBA. By all means we should enable it in CI, but not for users and
not for folks packaging it in distros.
Remove it from the flags in meson.build, and use mesons built in option
to enable it only in CI.
See:
https://embeddedartistry.com/blog/2017/05/22/werror-is-not-your-friend/
I plan to package CDBA in Alpine soon, having build tests for it in CI will help ensure that we avoid easy regressions like missing headers (yay musl..)

Add Alpine Linux CI and stop enabling werror for everyone

---

README
cdb_assist.c
cdba-server.c
cdba.c
config-samples/sample11.yaml
device.c
device.h
device_parser.c
meson.build
qcomlt_dbg.c
schema.yaml
status-cmd.c
status-cmd.h
status.c
status.h

The CDB Assist backend allows the user to request status updates, which includes voltage and current provided to the board.
By formalizing the structure of these updates, generate them at a fixed interval, and redirect them to a fifo for programmatic consumption we can make this information useful to 3rd party tools (e.g. for validation, analysis, or graphing).
The QcomLT Debugboard has a voltage and current sensor, so the same functionality is extended to support this backend natively as well.
Support for invoking an external "status command" is also introduced. This allow board-specific custom measurement mechanisms, such as reading voltage and current sensors from iio, custom USB/network protocols etc.

Programmatic access to remote power measurements

---

cdba-server.c

Granted all possible issues with SSH, especially in the remote and/or proxied labs, and possible issues with the board being present but failing to power up, it is useful to have a banner message once CDBA was started. This gives user a clear picture that the connection is fine and the server is trying to power up the board.

cdba-server: add CDBA-server banner to be output on startup

---

cdb_assist.c
fastboot.c
qcomlt_dbg.c

Drop trailing white-spaces and tabs.  No functional changes.

Clean trailing white-spaces

---

ci/archlinux.sh

Use latest (not compat) version of libftdi in install scripts for Arch Linux.

ci: switch to new libftdi on Arch Linux

---

ppps.c

funny joke about steel + water or something

ppps: check if ppps3_path is valid

---

config-samples/sample12.yaml
device.h
device_parser.c
drivers/laurent.c
meson.build
schema.yaml

Add support for the KernelChip Laurent-2 / Laurent-5 / Laurent-112 / Laurent-128 network-controlled relay arrays.

laurent: driver for KernelChip Laurent family of relays

---

cdba-server.c
device.c

cdba-server blocks if the board is locked by another session. Loop around the flock(), sleeping in the middle. This allows CDBA to break early if user closes the terminal (by killing SSH or by Ctrl-A-Q sequence).

Fix quitting if the board is locked

---

drivers/ftdi-gpio.c

Observed instability in controlling devices when OUTPUT_ENABLE wasn't enabled in the first step. I couldn't find any documented reason why this is, but the documentation does say: "FtdiOutput Pin always kept at 1".
Alpaca always keeps OUTUT_ENABLE as 1, and never turns it off. The documentation seems to imply it should always be left on. This change updates the open sequence so that the OUTPUT_ENABLE bit is set first.

ftdi_gpio: Turn on OUTPUT_ENABLE first

---

cdba.c

The purpose for providing different exit codes (2 vs 110) for timeout before or after fastboot was to allow tools invoking cdba to detect if the device arrived at and performed fastboot or not.
In most cases relying on the fastboot (USB) disconnect notification works fine, but in cases where the provided image fails to decompress the standard fastboot implementation will OKAY the transfer, fail to process the image and then return to process further fastboot requests.
This has been observed in cases where the image is too big, or when it contains a big endian kernel.
Change the logic to rely on the "FASTBOOT_DOWNLOAD" response to determine that we did reach fastboot and where able to upload the image and then something happened - i.e. "there's a problem with the image" vs "there's a setup …

cdba: Rely on fastboot completion rather than USB disconnect

---

.github/workflows/ci.yml
status.c

- Update CI configuration removing obsolete Ubuntu relase and adding new Fedora and Ubuntu releases.
- Use %lld to print time_t

Fix CI builds

---

README
cdba.c

I use CDBA for booting remote boards, but also sometimes to boot locally attached boards. In that case, the SSH tunnel is pointless (and I don't have a SSH server set up on my laptop). Add an option to start the cdba-server locally without SSH if the host is omitted.
Also add an option to disable the total timeout (`-t 0`). I also sometimes use CDBA to power on a personal board remotely. Without specifying a boot.img, it boots into my installed Linux distro and then I access it via SSH. In that case, I don't want the board to power off while still being logged in.
See commit log for details.

cdba: Add option to run cdba-server locally without ssh and without timeout

---

cdba-server.c
cdba.c
cdba.h
device.c
device.h

Add special keys to allow triggering power and fastboot key presses from the cdba client. There is an option to send a short key "pulse" (press followed by release after 100ms) or to press/release keys separately:
- ctrl+a -> o: Send power key pulse
- ctrl+a -> O: Toggle power key (first use: press, next use: release)
- ctrl+a -> f: Send fastboot key pulse
- ctrl+a -> F: Toggle fastboot key (first use: press, next use: release)
In most cases you want to send the "pulse" (short key press), so it's helpful to have this mapped to a single key. This avoids forgetting to release the key again after pressing it.
The protocol between CDBA client and server is:
(MSG_KEY_PRESS <key:u8, state:u8>)
where key is either DEVICE_KEY_FASTBOOT (0) or DEVICE_KEY_POWER (1) and state is either …

cdba: Add keys to remotely press power or fastboot key

---

config-samples/sample8.yaml
drivers/ftdi-gpio.c
schema.yaml

Some boards have more than one USB port. In that case, there is a second
GPIO on the debug board to simulate a USB disconnection for those.
Add the option to describe both USB disconnect GPIOs using
"usb0_disconnect" and "usb1_disconnect" and change both of them
when disabling USB power.
In the future it might be useful to control them separately, but for now
this ensures that power to the board is cut properly when the board is
powered off.
Also fix some mistakes in `schema.yaml` that prevented actually validating the properties below `ftdi_gpio`.
Cc: @superna9999

drivers: ftdi-gpio: Add second USB disconnect GPIO & schema.yaml fixes

---

cdba-server.c
device.c
drivers/laurent.c
schema.yaml

It is possible to use Laurent relays to control USB mode, e.g. by attaching the relay to the onboard DIP switch on RB1 / RB2 boards. Extend the driver to support such configurations.

laurent: add support for controlling USB power
